name: Android CI

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build for 64-bit ARM (arm64-v8a)
    - name: Build APK for 64-bit ARM
      run: ./gradlew assembleRelease -PtargetAbi=arm64-v8a

    # Build for 32-bit ARM (armeabi-v7a)
    - name: Build APK for 32-bit ARM
      run: ./gradlew assembleRelease -PtargetAbi=armeabi-v7a

    # Create a release and upload APKs
    - name: Upload APKs to Release
      id: upload-release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/outputs/apk/release/app-arm64-v8a-release.apk
        asset_name: app-arm64-v8a-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: Upload APK for 32-bit ARM
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/outputs/apk/release/app-armeabi-v7a-release.apk
        asset_name: app-armeabi-v7a-release.apk
        asset_content_type: application/vnd.android.package-archive
